name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        required: false
        default: '1.3.0-bundle'

jobs:
  build:
    strategy:
      matrix:
        os: [ 'windows-latest' ] # 'ubuntu-latest' "ubuntu-18.04"
        python-version: ['3.8'] # [ '3.6', '3.7', '3.8', '3.9', '3.10' ]

    runs-on: ${{ matrix.os }}

    name: ${{ github.event.inputs.tag }} python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # install prerequisites
      - name: Preqrequisites Ubuntu-18.04
        if: matrix.os == 'ubuntu-18.04'
        run: |
          sudo apt install -q -y curl software-properties-common build-essential
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo apt-add-repository https://packages.microsoft.com/ubuntu/18.04/prod
          env DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y sudo -E apt install -q -y  libk4a1.4-dev

      - name: Preqrequisites Windows
        if: matrix.os == 'windows-latest'
        run: |
          wget https://download.microsoft.com/download/3/d/6/3d6d9e99-a251-4cf3-8c6a-8e108e960b4b/Azure%20Kinect%20SDK%201.4.1.exe -O sdk.exe
          ls -la .
          ./sdk.exe  /install /passive /norestart

      # run build command
      - name: Build pyk4a
        run: |
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          python setup.py bdist_wheel
          ls -la dist

      # upload dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.event.inputs.tag }}
          release_name: "Version ${{ github.event.inputs.tag }}"
          body: "Prebuilt pyk4a wheel packages version ${{ github.event.inputs.tag }}."
          overwrite: true
          file_glob: true
